config/routes.rb
Rails.application.routes.draw do
  get 'game/index'

  get 'board/index'
  get 'board/generate'

  get 'player/index'

  root 'game#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :player

  # after_create :initialize_state
  # after_create :build_battle_grid

  # http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html
  serialize :grid

  MATRIX_SIZE = 12

  FLEET = [5, 4, 3, 2, 2, 1]
  HORIZONTAL = 'O'
  VERTICAL = 'V'
  DIRECTION = [HORIZONTAL, VERTICAL]

  WATER = 0
  SHIP = 1
  MISS = 2
  HIT = 3

  def initialize
    super
    initialize_state
    build_battle_grid
  end

  def initialize_state
    self.grid = []
    (0...MATRIX_SIZE).each do |row|
      self.grid[row] = [WATER] * MATRIX_SIZE
    end
  end

  def build_battle_grid
    Board::FLEET.shuffle.each do |ship_length|
      space = available_placements(ship_length).sample
      place_ship(space[0], space[1], ship_length, space[2])
    end
  end

  # Places ship on battle grid
  def place_ship(x, y, length, direction)
    ship_coordinates = get_coordinates(x, y, length, direction)
    ship_coordinates.each do |space|
      self.grid[space[0]][space[1]] = SHIP
    end
  end

  def available_placements(length)
    available_placements = []
    self.grid.each_with_index do |x, xi|
      x.each_with_index do |y, yi|
        DIRECTION.each do |direction|
          if valid_placement?(xi, yi, length, direction)
            available_placements << [xi, yi, direction]
          end
        end
      end
    end

    available_placements
  end

  # Returns true if placement on grid and available
  def valid_placement?(x, y, length, direction)
    coordinates = get_coordinates(x, y, length, direction)
    return false if !coordinates

    coordinates.each do |coordinate|
      return false if self.grid[coordinate[0]][coordinate[1]] != WATER
    end
    true
  end

  def get_coordinates(x, y, length, direction)
    coordinates = []
    end_coordinate = calculate_end_coordinate(x, y, length, direction)

    return false if is_outside_of_grid?(end_coordinate[0], end_coordinate[1])

    (0...length).each do |size|
      case direction
        when HORIZONTAL
          coordinates << [x + size, y]
        when VERTICAL
          coordinates << [x, y + size]
      end
    end

    coordinates
  end


  def calculate_end_coordinate(start_x, start_y, length, direction)
    case direction
      when VERTICAL
        return [start_x, start_y + length]
      when HORIZONTAL
        return [start_x + length, start_y]
      else
        raise ArgumentError, "Direction '#{direction}' is invalid. Must be '#{VERTICAL}' or '#{HORIZONTAL}'"
    end
  end

  # Returns false if coordinate outside of grid
  def is_outside_of_grid?(x, y)
    return true if (x < 0 || x > Board::MATRIX_SIZE - 1)
    return true if (y < 0 || y > Board::MATRIX_SIZE - 1)
    false
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  has_one :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
    @board = Board.new
  end

  def generate
    redirect_to board_index_path
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/board/index.html.erb
<h1>Board#index</h1>

<%= link_to 'Generate', board_generate_path %>

<table>
  <tr>
    <td></td>
    <% ('A'..'Z').to_a.first(Board::MATRIX_SIZE).each do |col| %>
    <td>
      <%= col %>
    </td>
    <% end %>
  </tr>
  <% @board.grid.each_with_index do |x, xi| %>
    <tr>
      <td> <%= xi +1 %></td>
      <% x.each do |y| %>
        <td> <%= y.zero? ? 0 : y %> </td>
      <% end %>
      <tr>
  <% end %>

</table>

app/views/game/index.html.erb
<p align="middle"><i>Welcome to the "Battleship Game"</i> </p>
<%= image_tag("game.jpg", :alt => "rss feed", :size => "1820x900",
              :align=> "middle",

              :style => "border: 5px solid blue") %>
<%= button_to "New Game!", "/board/index", :method => "get", :align=> "middle" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BattleShips</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/player/index.html.erb
<h1>Player#index</h1>
<p>Find me in app/views/player/index.html.erb</p>